# Generated by Django 3.2.9 on 2021-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('language', models.CharField(max_length=25)),
                ('running_time', models.IntegerField()),
                ('rate', models.PositiveBigIntegerField()),
                ('release_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='photos%y%m%d')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
